[server]
enableWebsocketCompression = false
enableCORS = false
enableXsrfProtection = false

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

[browser]
gatherUsageStats = false

[global]
suppressDeprecationWarnings = true

[theme]
base = "light"
